---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64
  
steps:
- name: another
  image: node:18
  environment:
    CI_NPM_TOKEN:
      from_secret: CI_NPM_TOKEN
  commands:
  - echo "Hellos"
  - echo $CI_NPM_TOKEN | base64
  - echo "=== Starting test ==="
  # Setup .npmrc with HAR flat repository
  - echo "registry=https://pkg.harness.io/pkg/9UuUfLwaQ-6ZowvbG7qtLQ/npm/npm/" > .npmrc
  - echo "//pkg.harness.io/pkg/9UuUfLwaQ-6ZowvbG7qtLQ/npm/npm/:_authToken=$CI_NPM_TOKEN" >> .npmrc

  # Show .npmrc content for clarity
  - cat .npmrc

  # npm install the flat package
  - npm install test-package@0.0.1

   # Confirm it installed successfully
  - node -e "console.log('test-package installed successfully with UPPERCASE account ID!')"
